balias g 'git'
balias gcm 'git checkout master'
balias glog='git log --oneline --decorate --color --graph'
balias gp 'git push'
balias gst 'git status'
balias gup 'git pull --rebase'
balias time '/usr/bin/time -p'
